// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NCAA_Power_Ratings.Data;

#nullable disable

namespace NCAA_Power_Ratings.Migrations
{
    [DbContext(typeof(NCAAContext))]
    [Migration("20260430134929_UpdateAvgScoreDelta")]
    partial class UpdateAvgScoreDelta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("NCAA_Power_Ratings.Models.AvgScoreDelta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<byte>("AverageScoreDelta")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("AverageScoreDelta");

                    b.Property<int?>("SampleSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SampleSize");

                    b.Property<decimal>("StDevP")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("StDevP");

                    b.Property<byte>("Team1Wins")
                        .HasColumnType("tinyint")
                        .HasColumnName("Team1Wins");

                    b.Property<byte>("Team2Wins")
                        .HasColumnType("tinyint")
                        .HasColumnName("Team2Wins");

                    b.HasKey("Id");

                    b.ToTable("AvgScoreDeltas");
                });

            modelBuilder.Entity("NCAA_Power_Ratings.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("LPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LPoints");

                    b.Property<char>("Location")
                        .HasColumnType("TEXT")
                        .HasColumnName("Location");

                    b.Property<int>("LoserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LoserId");

                    b.Property<string>("LoserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LoserName");

                    b.Property<int>("WPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("WPoints");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Week");

                    b.Property<int>("WinnerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("WinnerId");

                    b.Property<string>("WinnerName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("WinnerName");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("NCAA_Power_Ratings.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TeamID");

                    b.Property<string>("Alias")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Alias");

                    b.Property<string>("Conference")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Conference");

                    b.Property<string>("ConferenceAbbr")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ConferenceAbbr");

                    b.Property<string>("Division")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Division");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TeamName");

                    b.HasKey("TeamID");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("NCAA_Power_Ratings.Models.TeamRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<decimal?>("BaseSOS")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("BaseSOS");

                    b.Property<decimal?>("CombinedSOS")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("CombinedSOS");

                    b.Property<byte>("Losses")
                        .HasColumnType("tinyint")
                        .HasColumnName("Losses");

                    b.Property<int>("PointsAgainst")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PointsAgainst");

                    b.Property<int>("PointsFor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PointsFor");

                    b.Property<decimal?>("SubSOS")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("SubSOS");

                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TeamID");

                    b.Property<byte>("Wins")
                        .HasColumnType("tinyint")
                        .HasColumnName("Wins");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("TeamID");

                    b.ToTable("TeamRecords");
                });

            modelBuilder.Entity("NCAA_Power_Ratings.Models.TeamRecord", b =>
                {
                    b.HasOne("NCAA_Power_Ratings.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
